# Generated by Django 2.1.5 on 2019-02-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_orders_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
