# Generated by Django 2.1.5 on 2019-02-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20190226_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
