# Generated by Django 2.1.5 on 2019-02-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20190226_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='orders',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
